# Generated by Django 3.0.8 on 2020-07-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200728_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(default='text', max_length=100, verbose_name='Message type'),
        ),
    ]
